# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 07:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import things.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0003_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 -']*$", 'Alphanumeric characters, dash, single-quote & space allowed.')])),
                ('realname', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 -']*$", 'Alphanumeric characters, dash, single-quote & space allowed.')])),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('imageurl', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FemaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 -']*$", 'Alphanumeric characters, dash, single-quote & space allowed.')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=things.models.FemaleModel.update_image_file)),
                ('insta', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 -']*$", 'Alphanumeric characters, dash, single-quote & space allowed.')])),
                ('mtype', models.CharField(choices=[('fs', 'Female Singer'), ('ms', 'Male Singer'), ('bs', 'Band/Duo/Group')], max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('languages', models.CharField(max_length=80)),
                ('genres', models.CharField(max_length=80)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=things.models.Musician.update_image_file)),
                ('insta', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 -']*$", 'Alphanumeric characters, dash, single-quote & space allowed.')])),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=20)),
                ('genres', models.CharField(max_length=80)),
                ('languages', models.CharField(max_length=80)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('imageurl', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RenameField(
            model_name='director',
            old_name='insta',
            new_name='imageurl',
        ),
        migrations.RemoveField(
            model_name='director',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='director',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='director',
            name='image',
        ),
        migrations.AddField(
            model_name='actor',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
