# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_auto_20190613_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultmodel',
            old_name='imageurl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='adultmodel',
            old_name='realname',
            new_name='real_name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='imageurl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='imageurl',
            new_name='image_url',
        ),
    ]
