# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 11:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0006_dancer_fitnessperson_sportsperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('genre', models.CharField(choices=[('dra', 'Drama'), ('scf', 'Sci-Fi'), ('thr', 'Thriller'), ('adv', 'Adventure'), ('ron', 'Romance'), ('co', 'Comedy'), ('rcm', 'Romcom'), ('fan', 'Fantasy'), ('sup', 'Superhero'), ('psy', 'Psychological Thriller'), ('lgl', 'Legal Drama'), ('mld', 'Military Drama'), ('mlt', 'Milirary Thriller'), ('his', 'Historical Fiction'), ('bio', 'Biopic'), ('doc', 'Documentary'), ('med', 'Medical Drama'), ('cor', 'Corporate'), ('dys', 'Dystopia'), ('uto', 'Utopia'), ('exp', 'Experimental'), ('noi', 'Film Noir'), ('mus', 'Musical'), ('oth', 'Others')], max_length=20)),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[1-9]\\d*$', 'Only Postive numbers allowed')])),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('genre', models.CharField(choices=[('dra', 'Drama'), ('scf', 'Sci-Fi'), ('thr', 'Thriller'), ('adv', 'Adventure'), ('ron', 'Romance'), ('co', 'Comedy'), ('rcm', 'Romcom'), ('fan', 'Fantasy'), ('sup', 'Superhero'), ('psy', 'Psychological Thriller'), ('lgl', 'Legal Drama'), ('mld', 'Military Drama'), ('mlt', 'Milirary Thriller'), ('his', 'Historical Fiction'), ('bio', 'Biopic'), ('doc', 'Documentary'), ('med', 'Medical Drama'), ('cor', 'Corporate'), ('dys', 'Dystopia'), ('uto', 'Utopia'), ('exp', 'Experimental'), ('noi', 'Film Noir'), ('mus', 'Musical'), ('oth', 'Others')], max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
