# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20190614_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='starring',
            field=models.ManyToManyField(blank=True, null=True, to='things.Actor'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='starring',
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(blank=True, null=True, to='things.Actor'),
        ),
    ]
