# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 20:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0010_auto_20190614_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('app_type', models.CharField(choices=[('ed', 'Educational'), ('sr', 'Subreddit'), ('yt', 'Youtube Channel'), ('nm', 'News & Magazine'), ('ut', 'useful Tools'), ('po', 'Portfolio'), ('pr', 'Programming'), ('ar', 'Art'), ('mo', 'Money')], max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 -']*$", 'Alphanumeric characters, dash, single-quote & space allowed.')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('genres', models.CharField(max_length=80)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('cuisine', models.CharField(choices=[('cn', 'Bengali'), ('cn', 'North Indian'), ('cn', 'South Indian'), ('fl', 'Japanese'), ('vl', 'French'), ('cd', 'Italian'), ('vl', 'Arabic'), ('vl', 'Mexian'), ('tw', 'Thai'), ('ct', 'Vietnamese'), ('vl', 'American'), ('vl', 'German'), ('vl', 'Persian'), ('vl', 'Chinese'), ('vl', 'British'), ('vl', 'Ethipian'), ('fp', 'Fictional Place')], max_length=20)),
                ('want_to_eat', models.BooleanField(default=False)),
                ('can_cook', models.BooleanField(default=False)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 -]*$', 'Alphanumeric characters, dash & space allowed.')])),
                ('last_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 -]*$', 'Alphanumeric characters, dash & space allowed.')])),
                ('dob', models.DateField(blank=True, default='01/01/89')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_actors', models.BooleanField(default=False)),
                ('show_directors', models.BooleanField(default=False)),
                ('show_writers', models.BooleanField(default=False)),
                ('show_artists', models.BooleanField(default=False)),
                ('show_musicians', models.BooleanField(default=False)),
                ('show_dancers', models.BooleanField(default=False)),
                ('show_sportspersons', models.BooleanField(default=False)),
                ('show_fitnesspersons', models.BooleanField(default=False)),
                ('show_femalemodels', models.BooleanField(default=False)),
                ('show_songs', models.BooleanField(default=False)),
                ('show_movies', models.BooleanField(default=False)),
                ('show_tvshows', models.BooleanField(default=False)),
                ('show_animes', models.BooleanField(default=False)),
                ('show_books', models.BooleanField(default=False)),
                ('show_foods', models.BooleanField(default=False)),
                ('show_youtubechannels', models.BooleanField(default=False)),
                ('show_websites', models.BooleanField(default=False)),
                ('show_apps', models.BooleanField(default=False)),
                ('show_videogames', models.BooleanField(default=False)),
                ('show_cars', models.BooleanField(default=False)),
                ('show_bikes', models.BooleanField(default=False)),
                ('show_adultmodels', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Musician')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('vehicle_type', models.CharField(choices=[('ca', 'Car'), ('bi', 'Bike'), ('ai', 'Aircraft'), ('wa', 'Watercraft'), ('ot', 'Others')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('site_type', models.CharField(choices=[('ed', 'Educational'), ('sr', 'Subreddit'), ('yt', 'Youtube Channel'), ('nm', 'News & Magazine'), ('ut', 'useful Tools'), ('po', 'Portfolio'), ('pr', 'Programming'), ('ar', 'Art'), ('mo', 'Money')], max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!;.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")])),
                ('channel_type', models.CharField(choices=[('tu', 'Tutorial'), ('ts', 'Talk Show Host'), ('ed', 'Educational'), ('en', 'Entertainment'), ('fo', 'Food'), ('so', 'Social'), ('te', 'Tech'), ('mx', 'Mixed')], max_length=20)),
                ('rank', models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
