# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0011_application_artist_food_profile_settings_song_vehicle_website_youtubechannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='song',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='website',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.DeleteModel(
            name='YoutubeChannel',
        ),
    ]
