# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 20:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0012_auto_20190616_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 -]*$', 'Alphanumeric characters, dash & space allowed.')])),
                ('last_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 -]*$', 'Alphanumeric characters, dash & space allowed.')])),
                ('dob', models.DateField(blank=True, default='01/01/89')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_actors', models.BooleanField(default=False)),
                ('show_directors', models.BooleanField(default=False)),
                ('show_writers', models.BooleanField(default=False)),
                ('show_artists', models.BooleanField(default=False)),
                ('show_musicians', models.BooleanField(default=False)),
                ('show_dancers', models.BooleanField(default=False)),
                ('show_sportspersons', models.BooleanField(default=False)),
                ('show_fitnesspersons', models.BooleanField(default=False)),
                ('show_femalemodels', models.BooleanField(default=False)),
                ('show_songs', models.BooleanField(default=False)),
                ('show_movies', models.BooleanField(default=False)),
                ('show_tvshows', models.BooleanField(default=False)),
                ('show_animes', models.BooleanField(default=False)),
                ('show_books', models.BooleanField(default=False)),
                ('show_foods', models.BooleanField(default=False)),
                ('show_youtubechannels', models.BooleanField(default=False)),
                ('show_websites', models.BooleanField(default=False)),
                ('show_apps', models.BooleanField(default=False)),
                ('show_videogames', models.BooleanField(default=False)),
                ('show_cars', models.BooleanField(default=False)),
                ('show_bikes', models.BooleanField(default=False)),
                ('show_adultmodels', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
