# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0013_profile_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessperson',
            name='image',
        ),
    ]
