# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0014_remove_fitnessperson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessperson',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
