# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0018_auto_20190616_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('owner', 'timestamp')},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('owner', 'timestamp')},
        ),
        migrations.AddField(
            model_name='settings',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default='1989-01-01', null=True),
        ),
    ]
