# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0019_auto_20190616_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='rank',
            field=models.CharField(blank=True, choices=[('a', '1'), ('b', '2'), ('c', '3'), ('d', '4'), ('e', '5')], max_length=12, null=True, unique=True),
        ),
    ]
