# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0020_auto_20190617_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('owner', 'timestamp'), 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together=set([('owner', 'rank')]),
        ),
    ]
