# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0022_auto_20190618_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultmodel',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='dancer',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='femalemodel',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='fitnessperson',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='sportsperson',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='tvshow',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AlterModelOptions(
            name='youtubechannel',
            options={'ordering': ('-rank', 'name')},
        ),
        migrations.AddField(
            model_name='adultmodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dancer',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='director',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='femalemodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fitnessperson',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musician',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportsperson',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writer',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='adultmodel',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='anime',
            unique_together=set([('owner', 'rank', 'anime_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='dancer',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='femalemodel',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='fitnessperson',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set([('owner', 'rank', 'cuisine')]),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='musician',
            unique_together=set([('owner', 'rank', 'mtype')]),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('owner', 'rank', 'place_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='sportsperson',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='tvshow',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('owner', 'rank', 'vehicle_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='website',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='writer',
            unique_together=set([('owner', 'rank')]),
        ),
        migrations.AlterUniqueTogether(
            name='youtubechannel',
            unique_together=set([('owner', 'rank')]),
        ),
    ]
