# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0025_auto_20190619_1245'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together=set([]),
        ),
    ]
