# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 18:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0027_auto_20190624_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='started_from',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[1-9]\\d*$', 'Only Postive numbers allowed')]),
        ),
        migrations.AlterField(
            model_name='anime',
            name='watch_status',
            field=models.CharField(choices=[('h', 'Watching'), ('w', 'Watched'), ('n', 'Not watched'), ('s', 'Started')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_status',
            field=models.CharField(choices=[('h', 'Watching'), ('w', 'Watched'), ('n', 'Not watched'), ('s', 'Started')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='watch_status',
            field=models.CharField(choices=[('h', 'Watching'), ('w', 'Watched'), ('n', 'Not watched'), ('s', 'Started')], max_length=20, null=True),
        ),
    ]
