# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0028_auto_20190625_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='started_from',
            field=models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[1-9]\\d*$', 'Only Postive numbers allowed')]),
        ),
    ]
