# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0029_anime_started_from'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together=set([]),
        ),
    ]
