# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0031_auto_20190625_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
