# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0033_auto_20190626_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adultmodel',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'Adult Models'},
        ),
        migrations.AlterModelOptions(
            name='audiogenre',
            options={'verbose_name_plural': 'Audio Genres'},
        ),
        migrations.AlterModelOptions(
            name='femalemodel',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'Female Models'},
        ),
        migrations.AlterModelOptions(
            name='fitnessperson',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'Fitness Persons'},
        ),
        migrations.AlterModelOptions(
            name='sportsperson',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'Sports Persons'},
        ),
        migrations.AlterModelOptions(
            name='tvshow',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'TV Shows'},
        ),
        migrations.AlterModelOptions(
            name='videogenre',
            options={'verbose_name_plural': 'Video Genres'},
        ),
        migrations.AlterModelOptions(
            name='youtubechannel',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'Youtube Channels'},
        ),
    ]
