# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0034_auto_20190626_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='things.VideoGenre'),
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='genre',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='genre',
            field=models.ManyToManyField(to='things.VideoGenre'),
        ),
    ]
