# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0036_auto_20190626_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiogenre',
            options={'ordering': ('name',), 'verbose_name_plural': 'Audio Genres'},
        ),
        migrations.AlterModelOptions(
            name='videogenre',
            options={'ordering': ('name',), 'verbose_name_plural': 'Video Genres'},
        ),
    ]
