# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0037_auto_20190626_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='watch_status',
            field=models.CharField(choices=[('h', 'Waiting for next release'), ('w', 'Completed all seasons'), ('s', 'Started watching'), ('n', 'Wish to start it someday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_status',
            field=models.CharField(choices=[('h', 'Watched it'), ('w', 'Watched it multiple times'), ('s', 'Watching it now'), ('n', 'Wish to watch it someday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='watch_status',
            field=models.CharField(choices=[('h', 'Waiting for next release'), ('w', 'Completed all seasons'), ('s', 'Started watching'), ('n', 'Wish to start it someday')], max_length=20, null=True),
        ),
    ]
