# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0038_auto_20190626_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='started_from',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='started_from',
        ),
    ]
