# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0039_auto_20190626_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_type',
            field=models.CharField(blank=True, choices=[('s', 'Series'), ('m', 'Movie')], default='s', max_length=20),
        ),
    ]
