# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 16:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0040_auto_20190626_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'Anime Series'},
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!();.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")]),
        ),
    ]
