# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 16:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0041_auto_20190727_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='writers',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator("^[a-zA-Z0-9 %&#?!();.,'+/*-]*$", "Alphanumeric characters, space and %&#?!;.,'+/*- are allowed.")]),
        ),
    ]
